<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>_301434046_eskim__Lab2</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.102.9" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.104.2" />
    <PackageReference Include="Syncfusion.PdfViewer.WPF" Version="35.1.39" />
  </ItemGroup>

</Project>
